services:
  cache:
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/cache:/data  
  web:
    build: .
    command: ["uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=cryptoclient.settings.prod     
  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "81:81"
  daphne:
    build: .
    working_dir: /code/cryptoclient/
    command: ["daphne", "-u", "/code/cryptoclient/daphne.sock",
              "cryptoclient.asgi:application"] 
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=cryptoclient.settings.prod
     

                