services:
  db:
    image: postgres:14.5
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cache:
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/cache:/data    
  web:
      build: .
      command: ["./wait-for-it.sh", "db:5432", "--",
            "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
      restart: always
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      environment:
        - DJANGO_SETTINGS_MODULE=cryptoclient.settings.prod
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      depends_on:
        - db 
        - cache
  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "81:81"
      - "443:443"       
  daphne:
      build: .
      working_dir: /code/cryptoclient/
      command: ["../wait-for-it.sh", "db:5432", "--",
                "daphne", "-u", "/code/cryptoclient/daphne.sock",
                "cryptoclient.asgi:application"] 
      restart: always
      volumes:
        - .:/code
      environment:
        - DJANGO_SETTINGS_MODULE=cryptoclient.settings.prod
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      depends_on:
        - db
        - cache      
  
   
      
       